### ISSUE TITLE
No Windows console found

### ISSUE THREAD

**Issue by ruicovelo** [awslabs/aws-shell#169] opened 2017-01-20 12:21 UTC
I am trying to run aws-shell on a Windows 10 box. I'm getting "No Windows console found. Are you running cmd.exe?". And yes, I am running cmd.exe.
[stack.txt](https://github.com/awslabs/aws-shell/files/719333/stack.txt)

**Comment by donnemartin** [comment] 2017-01-23 02:38
Hi @ruicovelo, thanks for the report.  I'm not able to reproduce, but I'll add some info here that might help us with investigating.

This issue might be related: https://github.com/jonathanslenders/python-prompt-toolkit/issues/406

A recent commit in the prompt-toolkit project seems to fix the NoConsoleScreenBufferError issue: https://github.com/jonathanslenders/python-prompt-toolkit/commit/d5d9e296cdd3e2b1e8126f6307a7c09d0bdcdd3a

**Comment by joguSD** [comment] 2017-07-31 20:29
I don't have a Windows 10 box to test this out. 
Could you try an updated version of prompt-toolkit and see if you're still having an issue?

**Comment by joguSD** [comment] 2017-08-23 21:18
@ruicovelo I tried using a 64bit version of Python 3.4 on a fresh install of Windows 10 and wasn't able to reproduce this error. I'm going to close this issue for now, but feel free to reopen it if you're still having issues.

**Closed by joguSD** 2017-08-23 21:18 UTC
Labels: bug
