### ISSUE TITLE
HTMLParser.HTMLParseError: unknown declaration: u'CDATA

### ISSUE THREAD

**Issue by johnbot1** [awslabs/aws-shell#108] opened 2016-01-22 18:48 UTC
I've been unable to get this working on a fully updated amazon ami. ideas?

[root@ ~]# aws-shell
First run, creating autocomplete index...
Traceback (most recent call last):
  File "/usr/local/bin/aws-shell", line 9, in <module>
    load_entry_point('aws-shell==0.1.0', 'console_scripts', 'aws-shell')()
  File "/usr/local/lib/python2.6/site-packages/awsshell/__init__.py", line 47, in main
    write_index(index_file)
  File "/usr/local/lib/python2.6/site-packages/awsshell/makeindex.py", line 63, in write_index
    index_command(current, help_command)
  File "/usr/local/lib/python2.6/site-packages/awsshell/makeindex.py", line 55, in index_command
    index_command(child, sub_help_command)
  File "/usr/local/lib/python2.6/site-packages/awsshell/makeindex.py", line 55, in index_command
    index_command(child, sub_help_command)
  File "/usr/local/lib/python2.6/site-packages/awsshell/makeindex.py", line 40, in index_command
    arg_obj.documentation.split('\n')[0])
  File "/usr/local/lib/python2.6/site-packages/awsshell/utils.py", line 22, in remove_html
    s.feed(html)
  File "/usr/lib64/python2.6/HTMLParser.py", line 108, in feed
    self.goahead(0)
  File "/usr/lib64/python2.6/HTMLParser.py", line 156, in goahead
    k = self.parse_declaration(i)
  File "/usr/lib64/python2.6/markupbase.py", line 96, in parse_declaration
    return self.parse_marked_section(i)
  File "/usr/lib64/python2.6/markupbase.py", line 161, in parse_marked_section
    self.unknown_decl(rawdata[i+3: j])
  File "/usr/lib64/python2.6/HTMLParser.py", line 361, in unknown_decl
    self.error("unknown declaration: %r" % (data,))
  File "/usr/lib64/python2.6/HTMLParser.py", line 115, in error
    raise HTMLParseError(message, self.getpos())
HTMLParser.HTMLParseError: unknown declaration: u'CDATA[&amp;', at line 1, column 213

**Comment by donnemartin** [comment] 2016-01-24 11:43
Looks like a duplicate of https://github.com/awslabs/aws-shell/issues/107.

**Comment by jamesls** [comment] 2016-05-19 23:32
Let's track this over in #107.  Closing as a dupe.

**Closed by jamesls** 2016-05-19 23:32 UTC
